FROM python:3.12-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container
RUN mkdir /app
COPY pyproject.toml uv.lock /app

# Install the application dependencies
WORKDIR /app
RUN uv sync --frozen --no-cache

COPY ./app /app/app

# Run the application
CMD [ "/app/.venv/bin/fastapi", "run", "/app/app/main.py", "--port", "80", "--host", "0.0.0.0" ]
